markup_highlight = 'underline="low" weight="bold"'
#markup_extra = 'foreground="blue"'
#markup_default = 'foreground="yellow"'
exclusive = false
lines = 2
icon_size = 64
anchor_left = false
anchor_right = false
anchor_top = false
anchor_bottom = false
#margin_top = 0
#margin_bottom = 0
#margin_left = 0
#margin_right = 0
width = 1300
height = 600
