[colors]
primary.foreground = "#fcfcfc"
primary.background = "#232323"
primary.dim_foreground = "#eff0f1"
primary.bright_foreground = "#ffffff"

normal.black =    "#232627"
normal.red =      "#ed1515"
normal.green =    "#11d116"
normal.yellow =   "#f67400"
normal.blue =     "#1d99f3"
normal.magenta =  "#9b59b6"
normal.cyan =     "#1abc9c"
normal.white =    "#fcfcfc"

bright.black =   "#7f8c8d"
bright.red =     "#c0392b"
bright.green =   "#1cdc9a"
bright.yellow =  "#fdbc4b"
bright.blue =    "#3daee9"
bright.magenta = "#8e44ad"
bright.cyan =    "#16a085"
bright.white =   "#ffffff"

dim.black =   "#31363b"
dim.red =     "#783228"
dim.green =   "#17a262"
dim.yellow =  "#b65619"
dim.blue =    "#1b668f"
dim.magenta = "#614a73"
dim.cyan =    "#186c60"
dim.white =   "#63686d"
