[Service]
PrivateUsers=true
PrivatePIDs=true
PrivateTmp=true
PrivateIPC=true

MountAPIVFS=true
BindLogSockets=true
ProtectProc=ptraceable
CapabilityBoundingSet=
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=tmpfs
ProtectHostname=true
ProtectClock=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectKernelLogs=true
ProtectControlGroups=true
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK
RestrictFileSystems=~@network
LockPersonality=true
RestrictSUIDSGID=true
SystemCallErrorNumber=EPERM
SystemCallArchitectures=x86-64 x86

# Home + Runtime dir
TemporaryFileSystem=%t /mnt
BindPaths=%h/Sandboxes/Steam/:%h

### Paths
# PulseAudio
BindReadOnlyPaths=-%h/.config/pulse/
BindReadOnlyPaths=-%t/pulse/
# PipeWire
BindReadOnlyPaths=-%h/.config/pipewire/
BindReadOnlyPaths=-%t/pipewire-0
BindReadOnlyPaths=-%t/pipewire-0.lock
# Wayland
BindReadOnlyPaths=-%t/wayland-1
BindReadOnlyPaths=-%t/wayland-1.lock
# X11
BindReadOnlyPaths=-/tmp/.X0-lock
BindReadOnlyPaths=-/tmp/.X11-unix/
# Systemd Resolved
BindReadOnlyPaths=-/run/systemd/resolve/stub-resolv.conf
# Theming
BindReadOnlyPaths=-%h/.gtkrc-2.0
# Potentially leaks stuff:
BindReadOnlyPaths=-%h/.config/dconf/
BindReadOnlyPaths=-%h/.config/fontconfig/
BindReadOnlyPaths=-%h/.config/gtk-2.0/
BindReadOnlyPaths=-%h/.config/gtk-3.0/
BindReadOnlyPaths=-%h/.config/gtk-4.0/
# XDG Dirs
BindReadOnlyPaths=-%h/.config/user-dirs.dirs

# User DBus (needed by steam)
BindReadOnlyPaths=%t/bus
# Steam Folders
BindPaths=%h/.steam/
BindPaths=%h/.local/share/Steam/
BindPaths=%h/Games/Steam/
BindPaths=/mnt/wgames/SteamLibrary/
BindPaths=/mnt/windows/Program\ Files\ \(x86\)/Steam/steamapps/
# Vulkan Layers
BindPaths=%h/.local/share/vulkan/implicit_layer.d
