#!/bin/bash

#########################################################################
# Arguments
#########################################################################
declare -a args
# Enable wl-drm interface until applications are fixed
#args+=(-Dlegacy-wl-drm)

#########################################################################
# XDG Variables
#########################################################################
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=sway

#########################################################################
# GUI Frameworks/Applications
#########################################################################
export SDL_VIDEODRIVER="wayland,x11"
export QT_QPA_PLATFORM="wayland"
export QT_STYLE_OVERRIDE=Adwaita-Dark
export MOZ_ENABLE_WAYLAND=1
export _JAVA_AWT_WM_NONREPARENTING=1

#########################################################################
# NVIDIA Stuff
#########################################################################
# OpenGL Variables
#export GBM_BACKEND=nvidia-drm
#export __GL_GSYNC_ALLOWED=0
#export __GL_VRR_ALLOWED=0
#export __GLX_VENDOR_LIBRARY_NAME=nvidia

#export WLR_DRM_NO_ATOMIC=1
#export WLR_RENDERER=vulkan
#export WLR_NO_HARDWARE_CURSORS=1

# Required special arguments
#args+=(--unsupported-gpu)

##########################################################################
# Debug Stuff
#########################################################################
#debug_prefix="gdbserver 127.0.0.1:4444"
#export WLR_SCENE_DISABLE_DIRECT_SCANOUT=1
#args+=(-V -d)

exec $debug_prefix /usr/bin/sway "${args[@]}" "$@"
