#!/bin/bash

#########################################################################
# Arguments
#########################################################################
declare -a args
# Enable wl-drm interface until applications are fixed
args+=(-Dlegacy-wl-drm)

#########################################################################
# XDG Variables
#########################################################################
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=sway

#########################################################################
# GUI Frameworks/Applications
#########################################################################
export SDL_VIDEODRIVER=wayland
export QT_QPA_PLATFORM="wayland"
export QT_STYLE_OVERRIDE=Adwaita-Dark
export MOZ_ENABLE_WAYLAND=1
export _JAVA_AWT_WM_NONREPARENTING=1

#########################################################################
# Xwayland
#########################################################################
export WLR_XWAYLAND=~/.local/bin/Xwayland

#########################################################################
# NVIDIA Stuff
#########################################################################
# OpenGL Variables
#export GBM_BACKEND=nvidia-drm
#export __GL_GSYNC_ALLOWED=0
#export __GL_VRR_ALLOWED=0
#export __GLX_VENDOR_LIBRARY_NAME=nvidia

# Hardware cursors not yet working on wlroots
#export WLR_NO_HARDWARE_CURSORS=1
#export WLR_RENDERER=vulkan

# Required special arguments
#args+=(--unsupported-gpu)
#args+=(-Dnoscanout)

exec systemd-cat -t sway -- \\
     systemd-run --user --scope --slice=session.slice -u sway -- \\
     /usr/bin/sway "${args[@]}" "$@"
