#!/usr/bin/bash

#########################################################################
# NVIDIA Stuff
#########################################################################
#export XWAYLAND_NO_GLAMOR=1

exec systemd-cat -t Xwayland -- \
     /usr/bin/Xwayland "$@"
