import = [
    "~/.config/alacritty/color.toml"
]

ipc_socket = false

[env]
TERM = "xterm-256color"

[window]
opacity = 0.8
resize_increments = true

[keyboard]
bindings = [
    { key = "Q", mods = "Control", action = "Quit" }
]
